### ISSUE TITLE
SAML Protocol not working

### ISSUE THREAD

**Issue by greven** [pac4j/spark-pac4j#1]
SAML protocol not redirecting to the idp.

As described here: https://groups.google.com/forum/?fromgroups=#!topic/pac4j-users/iaOL56dDfN0

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/spark-pac4j/pull/2

**Comment by leleuj** [comment]
@greven: the fix has been merged, can you retest with the `spark-java` 1.0.1-SNAPSHOT version?

**Comment by greven** [comment]
Hi Jérôme,

You haven't released the artifact to Sonatype yet, right?
Once it's on Sonatype I will test it. Thanks for the quick fix by the way!

**Comment by leleuj** [comment]
Yes, it is already deployed on Sonatype: https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/spark-pac4j/1.0.1-SNAPSHOT/ (at every build)

I'm waiting for your feedback to perform the release which will be available in the Maven central repository.

**Comment by greven** [comment]
Hey ,

I'm getting an error with your SNAPSHOT build that I don't get by using 1.0.0.

    Exception in thread "main" java.lang.NoClassDefFoundError: org/pac4j/sparkjava/CallbackRoute
	    at com.sap.swdc.webserver.authentication.Authentication.<init>(Authentication.java:35)
	    at com.sap.swdc.webserver.Routing.<init>(Routing.java:25)
	    at com.sap.swdc.webserver.Server.main(Server.java:22)
    Caused by: java.lang.ClassNotFoundException: org.pac4j.sparkjava.CallbackRoute
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	    ... 3 more

Intellij doesn't give me any importing errors, but always NoClassDefFoundError when starting the server.

**Comment by leleuj** [comment]
Very strange! This class has not been changed between version 1.0.0 and 1.0.1-SNAPSHOT and it works in the demo: https://github.com/pac4j/spark-pac4j-demo

Can you try the demo and tell me if you get the same error?

**Comment by greven** [comment]
The Demo works, it gives an error on TestShib saying Error Message: Message did not meet security requirements, but that should be a configuration problem.
I guess the problem is on my side then.

Regarding the issue i think it is fixed since now it redirected correcly to the IdP!

**Comment by leleuj** [comment]
That was my conclusion also. So your issue is even stranger. I guess we're good to go. I will release a version 1.0.1 and you'll be able to test the fix with it.

**Comment by greven** [comment]
There is something else that I don't think it works. It's not a big problem but if you want to use a link to authenticate with SAML instead of using the Filter (RequiresAuthenticationFilter) I think it is not working, not on the demo nor in my application (although I'm not making use of it).

In the demo if you try to authenticate using a direct link it still says it needs client redirection and it doesn't actually redirect you to the IdP. The link generated in the demo is: http://localhost:8080/callback?client_name=Saml2Client&needs_client_redirection=true

**Comment by leleuj** [comment]
You're right: I should have checked that as well. Will fix and release (again)!

**Comment by leleuj** [comment]
Fixed again: https://github.com/pac4j/spark-pac4j/pull/3

**Comment by leleuj** [comment]
The 1.0.2 release is now available on the Maven central repository to fix the issues.
