### ISSUE TITLE
Request#body becomes blank when SecurityFilter added 

### ISSUE THREAD

**Issue by jrrl** [pac4j/spark-pac4j#19]
Whenever I add a SecurityFilter to a path, the Request#body becomes blank. In fact, the entire Request object becomes uninitialized, and you have to use Request#raw to get the underlying HttpServletRequest. 

Code: 
```
HeaderClient headerClient = new HeaderClient("Authorization", jwtAuthenticator);
Clients clients = new Clients(headerClient);
Config config = new Config(clients);
config.setHttpActionAdapter(new DefaultHttpActionAdapter());
config.addAuthorizer("admin", new RequireAnyRoleAuthorizer<>("ROLE_ADMIN");

before(((request, response) -> log.trace("Received API Call: {} {}", request.requestMethod(), request.contextPath())));
before("/api/users/*", new SecurityFilter(config, "HeaderClient", "admin"));

post("/api/users", (request, response) -> {
    log.debug("Request body: {}", request.body()); // will show up as blank 
   // ... do something
});
```

**Comment by jrrl** [comment]
Okay, I just tested it again, and weirdly enough, if I call Request#body in a before filter _before_ I add the security filter, it works perfectly. 

```
before("/api/users/*", (request, response) -> log.debug("Request body: {}", request.body())); <-- call Request#body before the security filter
before("/api/users/*", new SecurityFilter(config, "HeaderClient", "admin"));
post("/api/users", (request, response) -> {
    log.debug("Request body: {}", request.body()); // will now work properly
   // ... do something
});
```

**Comment by leleuj** [comment]
This is really strange. I will do some tests.

**Comment by leleuj** [comment]
I cannot reproduce the issue. I updated the demo with the `/body` endpoint: https://github.com/pac4j/spark-pac4j-demo/commit/bebf0555370035b0dd0850e10da1475e003e8a27

I use a `HeaderClient` like you:

```java
HeaderClient headerClient = new HeaderClient("Authorization", (credentials, ctx) -> {
  final String token = ((TokenCredentials) credentials).getToken();
  if (CommonHelper.isNotBlank(token)) {
    final CommonProfile profile = new CommonProfile();
    profile.setId(token);
     credentials.setUserProfile(profile);
  }
});
```

```java
before("/body", new SecurityFilter(config, "HeaderClient"));
post("/body", (request, response) -> {
    logger.debug("Body: " + request.body());
    return "done: " + getProfiles(request, response);
});
```

I send a body and an `Authorization` header and the body is displayed in the logs while the authentication works.

Can you test my demo and tell me if it works for you? Just to try to pinpoint where the issue is.

**Comment by jrrl** [comment]
Hi, I checked out the demo and tried out the code you used, and it's still returning blank for me. I even ran it with the debugger and when I looked inside the request object, and it was null. 

Log files: 
`SPARK PAC4J DEMO 21:47:25.930 [qtp1530621925-17] DEBUG org.pac4j.demo.spark.SparkPac4jDemo - Body: `

**Comment by leleuj** [comment]
OK. Even stranger. Can you give me details about your environment? OS? Java version? ...

**Comment by jrrl** [comment]
I'm running Windows 7, java version = 1.8.0_45. I ran the code using both IntelliJ and through the command line and they both say the same thing. I'll try doing it tomorrow in a different computer, maybe my environment really is the cause.

**Comment by leleuj** [comment]
I'm using MacOS. I wish it could explain the issue, but it seems somehow unlikely. Keep me posted...

**Comment by leleuj** [comment]
BTW, can you test the new version 2.0.0-SNAPSHOT to test if you've got the same problem?

**Comment by jrrl** [comment]
Is the 2.0.0-RC2 snapshot available on maven? I only see the RC1 snapshot when I check mvnrepository

**Comment by leleuj** [comment]
In the Sonatype snapshots repository in fact: https://github.com/pac4j/spark-pac4j-demo/blob/master/pom.xml#L10

**Comment by leleuj** [comment]
Any update on this? I'm releasing the 2.0.0-RC2 version if you want to do new tests...

**Comment by leleuj** [comment]
No feedback. Considered solved. Closing

**Comment by buckelieg** [comment]
It is still in a way. With indirecti form client at least :(
