### ISSUE TITLE
ClassNotFound - ClassLoader

### ISSUE THREAD

**Issue by jsauvain** [pac4j/spark-pac4j#23]
Hello, I'm Actually using Spark-Java with pac4j as a module on a module based application. Because the module does not have an own ClassLoader, the Class org.pac4j.core.profile.CommonProfile will not be found. Why? The Class is actually shaded into the module.

**Comment by leleuj** [comment]
"module", you mean OSGI module? `CommonProfile` is in the `pac4j-core` module, maybe you'll need an explicit dependency...

**Comment by jsauvain** [comment]
Another Application is loading the spark module into the classpath using an urlclassloader. After that a start method from the module is called. A reflection method in pac4j is causing an exception. If you change the reflection constructor into a static one, everything works fine.

**Comment by leleuj** [comment]
As you may see in the `getConstructor` method, we tried many ways to find the appropriate constructor: maybe there is an issue in the classloader order. Can you do some debugging inside the `getConstructor` method?
