### ISSUE TITLE
SecurityFilter wipes out request body

### ISSUE THREAD

**Issue by buckelieg** [pac4j/spark-pac4j#27]
Whenever SecurityFilter is established (with indirect client configured) before an URL which is used, for example, to upload/put/post data  it wipes request body after redirection loop is done (with FormClient).

**Comment by leleuj** [comment]
OK. The same issue was already reported, but it went nowhere.

Do you face the same issue with the demo: https://github.com/pac4j/spark-pac4j-demo?

Can you clarify which version you use so I can try to reproduce the issue?

**Comment by buckelieg** [comment]
I  will test demo and provide my example on this  on forthcoming weekend. If you don't mind. Thank you.

**Comment by buckelieg** [comment]
Ok I've got created test project that reproduces the case. How can I deliver it to you?

**Comment by leleuj** [comment]
The best option would be to update the spark-pac4j-demo so that I can check this issue every time I test the library before a release...

**Comment by leleuj** [comment]
I will try to find some time to work on that at the end of the week...

**Comment by buckelieg** [comment]
That test implies HeaderClient is present in configuration. 
The issue is that if you have configured  the FromClient **ONLY** - the body is wiped out because authorization hook is present.
During the hook it is checked if client profile present in the session and redirects back to original URL wiping out original request body.

**Comment by leleuj** [comment]
The `HeaderClient` and `FormClient` are two different types of clients: the first one is direct, the second one indirect.
It means that with a `FormClient`, you'll be redirected to a login form and then back to the originally requested URL.
The point is that the URL redirection is only a GET (and not a POST): https://github.com/pac4j/pac4j/issues/1074
So the body is not sent again and I think it explains the issue you encounter.

**Comment by buckelieg** [comment]
Yes, I understand the differences between direct and indirect clients.
But still if i configure FormClient solely (without any additional clients) - request body is wiped out.
I can consider for now adding HeaderClient as workaround, but this issue is still needed to be fixed.
I propose to save request body to the session (which might be created at login hook phase) and then (when login is succeeded using ForomClient) restore body from the session.
Thank you.

**Comment by leleuj** [comment]
Yes, it's exactly the idea, we should save the request in a more complete way (method, body, ...) in the session and reuse it.
For now, as a workaround, I think, you can use the `DirectFormClient`, it accepts form input parameters...

**Comment by leleuj** [comment]
Issue opened on pac4j: https://github.com/pac4j/pac4j/issues/1074
