### ISSUE TITLE
DIGEST authentication for sparkjava

### ISSUE THREAD

**Issue by RamakrishnanOSS** [pac4j/spark-pac4j#56]
Do we already have DIGEST authentication mechanism for SparkJava?

if so, can you share us some samples?

**Comment by leleuj** [comment]
Please use the mailing list for questions.

There is a `DirectDigestAuthClient` in the `pac4j-http` module for digest authn mechanism in pac4j which can be used in SparkJava.

The documentation is missing, but it is not too complicated.

**Comment by leleuj** [comment]
The tests can give you some examples nonetheless: https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/test/java/org/pac4j/http/client/direct/DirectDigestAuthClientTests.java
